# Site settings
title: Responsible Artificial Intelligence in Mental Health (Invited Workshop)
email: ganz@di.ku.dk
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
